### PR TITLE
Fix instrument range bug

### LINKED ISSUE #168: Global instrument range
**Describe the bug**
You can sometimes play music for vikings that are not in range.

**To Reproduce**
I do not know how to reproduce this at the moment but should be investigated.

**Expected behavior**
You should only be able to play music to vikings within the music AoE.

**Additional context**
The issue seems to be that the vikings aren't registered exiting the AoE.

### PR DESCRIPTION
**Pull request by smeas**
Closes #168 

**Description**  
There seem to be some kind of undocumented behaviour where if you reparent the rigidbody, it re-enters all collisions without exiting them first. To mitigate this, I clear the list of vikings before reparenting.

I also fixed an issue where vikings are added multiple times to the list.

### CODE REVIEW

File: Assets/00_Content/Scripts/Interactables/Instruments/Instrument.cs [hunk 1]
```diff
@@ -97,10 +117,19 @@ public class Instrument : PickUp, IUseable, IDesirable {
...
-			if (viking != null) {
-				vikingsInRange.Remove(viking);
-				if (isPlaying)
-					viking.CancelAffect(usingPlayer, this);
+			if (viking == null) return;
+
+			if (vikingsInRange.ContainsKey(viking)) {
+				int value = --vikingsInRange[viking];
+				if (value <= 0) {
+					vikingsInRange.Remove(viking);
```
Comment (MrJackey) [inline Assets/00_Content/Scripts/Interactables/Instruments/Instrument.cs:125]: This is scary, would having a separate layer (I know, so many layers...) for instrument AoE to collide with vikings only be nicer? It seems to collide with a viking's all different colliders

Comment (smeas) [reply Assets/00_Content/Scripts/Interactables/Instruments/Instrument.cs:125]: Not any scarier than what we had before. It's basically doing the same thing but storing it differently.
But yes, I thought about that, but like... layers... I would probably need to add 2 new layers in that case. I also thought about tags, but it seemed like that would also be pretty nasty.

**Review by MrJackey — APPROVED** [review]
:shipit:
